spring:
  datasource:
    username: root
    password: Shivam21@sahu
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
